# Generated by Django 4.2.6 on 2023-11-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gasto_administracion', '0002_alter_gastoadministracion_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gastoadministracion',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='gastoadministracion',
            name='monto',
            field=models.FloatField(verbose_name='Monto'),
        ),
    ]
