# Generated by Django 4.2.6 on 2023-10-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expensa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=100)),
                ('monto_total_sueldos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_total_arreglos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_total_gastos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidades', models.ManyToManyField(to='unidades.unidad')),
            ],
        ),
    ]
