# Generated by Django 4.2.6 on 2023-10-17 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expensas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensa',
            name='monto_total_arreglos',
        ),
        migrations.RemoveField(
            model_name='expensa',
            name='monto_total_gastos',
        ),
        migrations.RemoveField(
            model_name='expensa',
            name='monto_total_sueldos',
        ),
    ]
