# Generated by Django 4.2.6 on 2023-10-14 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edificio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_unidad', models.CharField(max_length=10)),
                ('tamano', models.DecimalField(decimal_places=2, max_digits=10)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificio.edificio')),
            ],
        ),
    ]
