# Generated by Django 4.2.6 on 2023-10-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unidades', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='tamano',
            field=models.CharField(choices=[('A', 'Tipo A (grande)'), ('B', 'Tipo B (chico)')], max_length=50, verbose_name='Elija el tipo de unidad'),
        ),
    ]
