# Generated by Django 4.2.6 on 2023-10-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=50, verbose_name='Apellido')),
                ('cuil', models.CharField(max_length=13, unique=True, verbose_name='Cuil')),
                ('telefono', models.CharField(max_length=50, unique=True, verbose_name='Telefono')),
                ('domicilio', models.CharField(help_text='Ej: Calle y número', max_length=50, verbose_name='Domicilio')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('sueldo_base', models.FloatField(verbose_name='Sueldo base')),
                ('horario', models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Noche', 'Noche')], max_length=50, verbose_name='Horario')),
            ],
        ),
    ]
