# Generated by Django 4.2.6 on 2023-10-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo', '0001_initial'),
        ('empleado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='trabajo',
            field=models.ManyToManyField(to='trabajo.trabajo'),
        ),
    ]
