# Generated by Django 4.2.6 on 2023-11-02 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo', '0002_alter_trabajo_descripcion'),
        ('empleado', '0002_empleado_trabajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='trabajo',
        ),
        migrations.AddField(
            model_name='empleado',
            name='trabajo',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='trabajo.trabajo'),
        ),
    ]
