# Generated by Django 4.2.6 on 2023-11-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arreglo', '0003_alter_arreglo_costo_alter_arreglo_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arreglo',
            name='costo',
            field=models.FloatField(verbose_name='Costo'),
        ),
    ]
