# Generated by Django 4.2.6 on 2023-10-21 00:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajo',
            name='descripcion',
            field=ckeditor.fields.RichTextField(help_text='Ingrese la descripción del trabajo'),
        ),
    ]
